api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "b2b-cart-transform"
type = "cart_transform"
uid = "9c041440-7632-1e76-661e-e61c122b8713baed26ee"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/app/sync"
  details = "/app/sync"
